Document: xtrabackup
Title: Debian xtrabackup Manual
Author: <insert document author here>
Abstract: This manual describes what xtrabackup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xtrabackup/xtrabackup.sgml.gz

Format: postscript
Files: /usr/share/doc/xtrabackup/xtrabackup.ps.gz

Format: text
Files: /usr/share/doc/xtrabackup/xtrabackup.text.gz

Format: HTML
Index: /usr/share/doc/xtrabackup/html/index.html
Files: /usr/share/doc/xtrabackup/html/*.html


